slam_toolbox_ai:
  ros__parameters:
    use_sim_time: true
    use_lifecycle_manager: false
    mode: mapping
    scan_topic: /scan_slam
    base_frame: base_link
    odom_frame: odom_ai
    map_frame: map_ai
    publish_tf: true
    publish_map: true
    publish_pose: true
    resolution: 0.05
    max_laser_range: 6.0
    minimum_time_interval: 0.10
    transform_timeout: 0.20
    tf_buffer_duration: 30.0
    map_update_interval: 2.0
    enable_interactive_mode: false
